-- ---------- extensions ----------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------- TABLES ----------
CREATE TABLE IF NOT EXISTS public.admin_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.api_keys (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key text,
  value text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  icon_name text NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT timezone('utc', now()),
  updated_at timestamptz DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  content text NOT NULL,
  read_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.educator_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  description text,
  about_business text,
  image text,
  website text,
  address text,
  phone text,
  facebook_url text,
  instagram_url text,
  youtube_url text,
  ai_chatbot varchar,
  ai_voice_agent jsonb DEFAULT '{"voice_id":"cjVigY5qzO86Huf0OWal","knowledge_base":[]}'::jsonb,
  categories text[] DEFAULT ARRAY[]::text[],
  tags text[] DEFAULT ARRAY[]::text[],
  is_active boolean DEFAULT true,
  is_featured boolean,
  last_active timestamptz,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.environment_variables (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL,
  value text NOT NULL,
  description text,
  is_encrypted boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.field_permissions (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.lesson_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  educator_id uuid NOT NULL,
  educator_profile_id uuid NOT NULL,
  proposed_date timestamptz NOT NULL,
  proposed_time time,
  message text,
  message_from_educator text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  educator_id uuid NOT NULL,
  type text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  start_date timestamptz NOT NULL DEFAULT timezone('utc', now()),
  end_date timestamptz,
  current_period_start timestamptz NOT NULL DEFAULT timezone('utc', now()),
  current_period_end timestamptz NOT NULL,
  auto_renew boolean NOT NULL DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.membership_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  membership_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD',
  status text NOT NULL,
  payment_method text NOT NULL,
  transaction_id text,
  payment_date timestamptz NOT NULL DEFAULT timezone('utc', now()),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  metadata jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.profile_views (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  educator_profile_id uuid NOT NULL,
  viewer_id uuid,
  ip_address text,
  viewed_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  educator_id uuid NOT NULL,
  student_id uuid NOT NULL,
  rating integer NOT NULL,
  review_text text,
  created_at timestamptz DEFAULT timezone('utc', now()),
  updated_at timestamptz DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.review_reactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  review_id uuid,
  user_id uuid,
  reaction_type text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.review_replies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  review_id uuid,
  user_id uuid,
  reply_text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.stripe_transactions (
  id text PRIMARY KEY,
  customer_email text NOT NULL,
  customer_name text NOT NULL,
  amount bigint NOT NULL,
  currency text NOT NULL DEFAULT 'usd',
  status text NOT NULL,
  payment_method text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.student_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  email text NOT NULL,
  name text,
  phone text,
  address text,
  favorites jsonb,
  is_active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.support_submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  issue_type text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'new',
  reference_id char(10),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------- FUNCTIONS ----------
CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid)
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = $1);
$$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = timezone('utc', now()); RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF new.raw_user_meta_data->>'user_type' = 'student' THEN
    INSERT INTO public.student_profiles (user_id, email) VALUES (new.id, new.email);
  END IF;
  RETURN new;
END; $$;

CREATE OR REPLACE FUNCTION public.get_profile_view_count(educator_id uuid)
RETURNS TABLE(total_views bigint, unique_views bigint, last_24h_views bigint)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY
  SELECT count(*)::bigint,
         count(DISTINCT coalesce(viewer_id::text, ip_address))::bigint,
         count(*) FILTER (WHERE viewed_at > now() - interval '24 hours')::bigint
  FROM public.profile_views WHERE educator_profile_id = educator_id;
END; $$;

-- ---------- AUTH TRIGGER ----------
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------- ENABLE RLS ----------
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.educator_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.environment_variables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stripe_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_submissions ENABLE ROW LEVEL SECURITY;

-- ---------- RLS POLICIES ----------
CREATE POLICY "Allow admins to read admin_users" ON public.admin_users
  FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));

CREATE POLICY "Allow public read access" ON public.api_keys FOR SELECT USING (true);

CREATE POLICY "Anyone can read categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Admins can insert categories" ON public.categories FOR INSERT TO authenticated
  WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Admins can update categories" ON public.categories FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins can delete categories" ON public.categories FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()));

CREATE POLICY "Users can read their own messages" ON public.chat_messages FOR SELECT TO authenticated
  USING (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)) AND deleted_at IS NULL);
CREATE POLICY "Users can insert messages" ON public.chat_messages FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Users can delete their own messages" ON public.chat_messages FOR UPDATE TO authenticated
  USING (auth.uid() = sender_id) WITH CHECK (deleted_at IS NULL);

CREATE POLICY "Public read educator profiles" ON public.educator_profiles FOR SELECT USING (true);
CREATE POLICY "Insert own educator profile" ON public.educator_profiles FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Update own educator profile" ON public.educator_profiles FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Delete own educator profile" ON public.educator_profiles FOR DELETE TO authenticated
  USING (auth.uid() = user_id);
CREATE POLICY "Admins update all educator profiles" ON public.educator_profiles FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Read student profiles" ON public.student_profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Insert own student profile" ON public.student_profiles FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Update own student profile" ON public.student_profiles FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins update all student profiles" ON public.student_profiles FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Anyone can read reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Students can create reviews" ON public.reviews FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM student_profiles WHERE user_id = auth.uid()));
CREATE POLICY "Students update own reviews" ON public.reviews FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM student_profiles WHERE user_id = auth.uid() AND id = reviews.student_id));
CREATE POLICY "Students delete own reviews" ON public.reviews FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM student_profiles WHERE user_id = auth.uid() AND id = reviews.student_id));

CREATE POLICY "Read reactions" ON public.review_reactions FOR SELECT USING (true);
CREATE POLICY "Insert own reaction" ON public.review_reactions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Update own reaction" ON public.review_reactions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Delete own reaction" ON public.review_reactions FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Read replies" ON public.review_replies FOR SELECT USING (true);
CREATE POLICY "Insert own reply" ON public.review_replies FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Update own reply" ON public.review_replies FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Delete own reply" ON public.review_replies FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Students view own lesson requests" ON public.lesson_requests FOR SELECT TO authenticated
  USING (student_id = auth.uid());
CREATE POLICY "Educators view own lesson requests" ON public.lesson_requests FOR SELECT TO authenticated
  USING (educator_id = auth.uid());
CREATE POLICY "Students create lesson requests" ON public.lesson_requests FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Both update lesson requests" ON public.lesson_requests FOR UPDATE TO authenticated
  USING (educator_id = auth.uid() OR student_id = auth.uid());

CREATE POLICY "Anyone can insert profile views" ON public.profile_views FOR INSERT WITH CHECK (true);
CREATE POLICY "Educators view own profile views" ON public.profile_views FOR SELECT
  USING (auth.uid() IN (SELECT user_id FROM educator_profiles WHERE id = profile_views.educator_profile_id));

CREATE POLICY "View own memberships" ON public.memberships FOR SELECT
  USING (educator_id IN (SELECT id FROM educator_profiles WHERE user_id = auth.uid()));
CREATE POLICY "Insert own memberships" ON public.memberships FOR INSERT
  WITH CHECK (educator_id IN (SELECT id FROM educator_profiles WHERE user_id = auth.uid()));
CREATE POLICY "Update own memberships" ON public.memberships FOR UPDATE
  USING (educator_id IN (SELECT id FROM educator_profiles WHERE user_id = auth.uid()));

CREATE POLICY "View own payments" ON public.membership_payments FOR SELECT
  USING (membership_id IN (SELECT m.id FROM memberships m JOIN educator_profiles e ON e.id = m.educator_id WHERE e.user_id = auth.uid()));

CREATE POLICY "Admin read stripe" ON public.stripe_transactions FOR SELECT TO authenticated
  USING (public.is_admin(auth.uid()));

CREATE POLICY "Anyone can submit support" ON public.support_submissions FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin insert env" ON public.environment_variables FOR INSERT
  WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Admin update env" ON public.environment_variables FOR UPDATE
  USING (public.is_admin(auth.uid()));
CREATE POLICY "Admin delete env" ON public.environment_variables FOR DELETE
  USING (public.is_admin(auth.uid()));

CREATE POLICY "Public read field_permissions" ON public.field_permissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admin all field_permissions" ON public.field_permissions FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()));

-- ---------- STORAGE BUCKET ----------
INSERT INTO storage.buckets (id, name, public)
VALUES ('business-images', 'business-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read business-images" ON storage.objects FOR SELECT
  USING (bucket_id = 'business-images');
CREATE POLICY "Authenticated upload business-images" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'business-images');
CREATE POLICY "Authenticated update own business-images" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'business-images' AND auth.uid()::text = (storage.foldername(name))[1]);
CREATE POLICY "Authenticated delete own business-images" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'business-images' AND auth.uid()::text = (storage.foldername(name))[1]);